version: "3"
services:
  bind9:
    image: volkerraschek/bind9-docker:latest
    ports:
    - 10053:53/tcp
    - 10053:53/udp
    volumes:
    - /etc/bind:/etc/bind
    - /etc/localtime:/etc/localtime
